project:
  type: website
  output-dir: docs
  
website:
  title: "Resources"
  navbar:
    logo: url(https://reefcloud.ai/static/media/coreLogoName.04eb209b6a92259208f9d8edb621bc4c.svg)
    left:
      - href: index.qmd
        text: Home
      - Collection.qmd
      - Analyses.qmd
      - Reporting.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/ReefCloud/resources
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Australian Institute of Marine Science"

format:
  html:
    theme: journal
    toc: true
    monobackgroundcolor: "#d42555"

editor: source

